# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Download_raster
                                 A QGIS plugin
 download_raster_gee
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-09
        copyright            : (C) 2022 by aleksi
        email                : alexis@odd.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os 
import platform
import pkg_resources
import site
import pathlib
import platform

from .scripts.utils import *

# try:
#     import retry
#     import rasterio
#     import tqdm
# except Exception as err:
#     system = platform.system()
#     if(system == 'Linux'):
        
#     if(system == 'Windows'):  
#         install_external_libs()
#         print(f'{err}')
     
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Download_raster class from file Download_raster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    pre_init_plugin()
    from .download_raster import Download_raster
    return Download_raster(iface)
